import os
import sys

try:
    import bpy
except ImportError as exc:
    raise SystemExit("Run this script with Blender Python, for example: blender -b school_campus.blend --python verify_school_campus.py") from exc


ROOT = os.environ.get("SCHOOL_ROOT", os.path.dirname(os.path.abspath(__file__)))
BLEND_PATH = os.environ.get("SCHOOL_BLEND", os.path.join(ROOT, "school_campus.blend"))
PREVIEW_DIR = os.environ.get("SCHOOL_PREVIEW_DIR", os.path.join(ROOT, "campus_previews"))
EXPECTED_PREVIEW_COUNT = 17

REQUIRED_KEYWORDS = [
    "微机室",
    "服务器机房",
    "配电室",
    "监控室",
    "保安室",
    "操场",
    "室内操场",
    "普通教室",
    "科技运维楼",
    "食堂",
    "宿舍",
    "STEM",
    "图书馆",
    "CCTV",
    "transformer",
    "fiber",
    "power",
    "中心水景",
    "物理实验室",
    "化学实验室",
    "生物实验室",
    "AI创客",
    "VR沉浸",
    "机器人",
    "报告厅",
    "校车",
    "自行车",
    "无障碍",
    "solar",
    "rainwater",
    "fire hydrant",
    "evacuation",
    "broadcast",
    "数字孪生",
    "楼层剖面",
    "食堂内部",
    "宿舍内部",
    "室内操场内部",
    "地下综合管廊",
    "疏散集结点",
    "校园围墙",
    "消防车道",
    "后勤装卸区",
    "垃圾分类站",
    "语言实验室",
    "美术教室",
    "音乐教室",
    "校史馆",
    "教师发展中心",
    "家长接待室",
    "卫生间",
    "电梯",
    "门禁",
    "校医诊室",
    "隔离观察室",
    "心理咨询室",
    "气象站",
    "空气质量",
    "图书馆内部",
    "阅览区",
    "自助借还机",
    "体育更衣室",
    "淋浴间",
    "体育器材室",
    "裁判医务点",
    "校园导视屏",
    "AED急救箱",
    "应急电话",
    "饮水点",
    "储物柜",
    "电子班牌",
    "访客服务终端",
    "充电服务站",
    "分区边界",
    "入口共享区",
    "教学静区",
    "运动活力区",
    "生活后勤区",
    "后勤车行门岗",
    "应急门",
    "访客停车场",
    "教职工停车场",
    "行政办公剖面",
    "校长室",
    "教务处",
    "总务处",
    "财务室",
    "档案室",
    "化学品暂存柜",
    "危废暂存箱",
    "通风橱",
    "紧急冲淋洗眼器",
    "生物安全柜",
    "空调能源站",
    "冷水机组",
    "循环水泵",
    "消防水池",
    "消防泵房",
    "生活水泵房",
    "弱电间IDF节点",
    "楼宇自控BAS",
    "一键日夜模式",
    "室外照明回路",
    "操场看台",
    "操场主席台",
    "操场电子记分屏",
    "跳远沙坑",
    "铅球投掷区",
    "露天剧场",
    "阅读花园",
    "生态课程湿地",
    "劳动教育菜园",
    "校园温室",
    "坐标网格",
    "指北针",
    "比例尺",
    "建筑编号",
    "楼层功能牌",
    "电子沙盘图层控制台",
    "电子沙盘图层_消防疏散",
    "电子沙盘图层_安防覆盖",
    "电子沙盘图层_网络拓扑",
    "电子沙盘图层_能源水务",
    "访客动线",
    "学生动线",
    "后勤动线",
    "无障碍连续动线",
    "消防登高面",
    "消防疏散总图",
    "安防覆盖总图",
    "网络拓扑总图",
    "能耗水务总图",
    "CCTV覆盖扇区",
    "地图索引图层控制",
    "年级分区牌",
    "教室编号",
    "班主任办公室",
    "备课室",
    "年级组办公室",
    "学生储物间",
    "课间灰空间",
    "风雨连廊",
    "55人智慧大教室样板",
    "四组双人桌",
    "学生座位",
    "抽屉书本",
    "漂亮地台",
    "中间黑板",
    "左触控屏",
    "右触控屏",
    "嵌入式讲台电脑",
    "屏幕右侧IO排线仓",
    "墙内线槽",
    "地面线槽",
    "后排黑板报",
    "LED灯带",
    "吊扇",
    "壁挂空调",
    "容量统计总表",
    "食堂后厨_收货验收区",
    "食堂后厨_冷库",
    "食堂后厨_干货库",
    "食堂后厨_粗加工间",
    "食堂后厨_烹饪区",
    "食堂后厨_备餐间",
    "食堂后厨_洗消间",
    "食堂后厨_留样柜",
    "食堂食品安全监测屏",
    "食堂洁污分流动线",
    "食堂餐盘回收口",
    "宿舍样板间_四人间",
    "宿舍公共卫生间",
    "宿舍淋浴间",
    "宿舍洗衣烘干房",
    "宿舍夜间值班室",
    "宿舍公共自习室",
    "宿舍生活导师室",
    "后勤仓储间",
    "清洁工具间",
    "维修工坊",
    "校服教材周转库",
    "后勤数字库存屏",
    "冷链卸货位",
    "厨余暂存冷藏箱",
    "油烟净化设备",
    "生活后勤洁污分流总图",
    "生活后勤完整运营",
    "体育馆_篮球主场",
    "体育馆_排球场",
    "体育馆_羽毛球场A",
    "体育馆_乒乓球区",
    "体育馆_体测区",
    "体育馆_健身房",
    "体育馆_瑜伽舞蹈房",
    "体育馆_可伸缩看台",
    "体育馆_赛事计分屏",
    "体育馆_急救AED运动医务点",
    "体育馆_运动数据采集屏",
    "室外排球场",
    "室外网球场",
    "室外体能训练区",
    "单双杠训练区",
    "体育教师办公室",
    "运动器材发放点",
    "运动损伤处理点",
    "夜跑步道照明",
    "运动健康总览牌",
    "体育健康完整系统",
    "周界入侵探测器",
    "访客证件核验终端",
    "车辆道闸车牌识别",
    "电子巡更点",
    "消防报警手报按钮",
    "烟感探测器",
    "应急照明疏散指示",
    "连廊防火卷帘",
    "消防报警联动主机",
    "安防事件联动平台",
    "应急物资仓库",
    "临时避险棚",
    "移动发电车接口",
    "卫星通信终端",
    "校园无线应急基站",
    "UPS不间断电源室",
    "储能电池舱",
    "微电网切换柜",
    "应急净水装置",
    "医疗救护集结帐篷",
    "韧性系统联动线",
    "校园应急指挥中心",
    "智慧安全韧性总览牌",
    "智慧安全韧性系统",
]


def main():
    if bpy.data.filepath != os.path.abspath(BLEND_PATH):
        bpy.ops.wm.open_mainfile(filepath=BLEND_PATH)
    names = [obj.name for obj in bpy.data.objects]
    missing = []
    for keyword in REQUIRED_KEYWORDS:
        count = sum(keyword.lower() in name.lower() for name in names)
        print(f"{keyword}: {count}")
        if count == 0:
            missing.append(keyword)
    print(f"OBJECT_COUNT: {len(names)}")
    preview_files = []
    contact_sheet = os.path.join(PREVIEW_DIR, "00_校园总览拼图.png")
    if os.path.isdir(PREVIEW_DIR):
        preview_files = sorted(
            f for f in os.listdir(PREVIEW_DIR)
            if f.endswith(".png") and f[:2].isdigit() and f != "00_校园总览拼图.png"
        )
    print(f"PREVIEW_COUNT: {len(preview_files)}")
    if len(preview_files) < EXPECTED_PREVIEW_COUNT:
        missing.append(f"preview images >= {EXPECTED_PREVIEW_COUNT}")
    if not os.path.exists(contact_sheet) or os.path.getsize(contact_sheet) == 0:
        missing.append("contact sheet")
    if missing:
        print("MISSING: " + ", ".join(missing))
        return 1
    print("VERIFY_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
